[build]
  command = "DISABLE_OG_IMAGE=true SKIP_IMAGE_OPTIMIZATION=true NODE_OPTIONS='--max-old-space-size=4096' pnpm build"
  publish = "dist"

[build.environment]
  SHARP_IGNORE_GLOBAL_LIBVIPS = "1"
  DISABLE_OG_IMAGE = "true"
  SKIP_IMAGE_OPTIMIZATION = "true"